### ISSUE TITLE
Radar speed & egomotion raw data

### ISSUE THREAD

**Issue by shawrby** [aimotive/aimotive-dataset-loader#1]
Hi,

Thank you for your awesome work!

1) Is the speed of radar raw data a relative speed with meter/second(m/s) unit?
How should the ego-motion compensated speed be extracted?

2) What's the meaning the each parameter and value in egomotion/egomotion2.json?

Thanks in advance.

**Comment by TamasMatuszka** [comment]
Hi,

I collected the answers to your questions.

The raw radar data is the radial speed with a meter/second unit, you can find the detailed sensor description here:
https://www.smartmicro.com/fileadmin/media/Downloads/Automotive_Radar/Sensor_Data_Sheets_76-81GHz/UMRR-11_Type_132_Automotive_Data_Sheet.pdf
You need the ego-motion only if you want to transform it into an absolute coordinate system.

egomotion.json parameters:
- key: camera frame id
- value: RT matrix from body coordinate system to ECEF

egmotion2.json parameters:
key: camera frame id (like in egomotion.json), value is a dictionary where:
- RT_ECEF_body is the same transformation matrix as in egomotion.json
- enh_sep is the latitude, longitude, height separation, i.e. GNSS error
- rph_sep is the roll, pitch, heading separation, i.e. IMU error
- time: GNSS+INS device timestamp
- time_host: synchronized host timestamp (from camera metadata)

**Comment by shawrby** [comment]
@TamasMatuszka 

Thank you for detailed reply!

But there is no egomotion2.json file in full dataset.
That is, only the egomotion.json file exists.

Therefore, ego-motion cannot be compensated with only RT_ECEF_body information.
Is my understanding correct?

**Comment by TamasMatuszka** [comment]
@shawrby 
You are right, not every sequence has an egomotion2.json file. However, egomotion.json also contains the RT_ECEF_body information that can be used for compensation (we also used it also during our experiments for collecting more than one LiDAR sweep).

If you check the egomotion.json and egomotion2.json in the data example, you can see that the first key-value pair in egomotion.json is the same as the key-RT_ECEF_body pair in the egomotion2.json file.

egomotion.json: 
"40": [-0.76755, 0.10175, 0.63286, 4071463.241, 0.05843, -0.9721, 0.22716, 1406636.117, 0.63832, 0.21133, 0.74019, 4688170.68283, 0.0, 0.0, 0.0, 1.0]

egomotion2.json:
"40": {"RT_ECEF_body": [[-0.76755, 0.10175, 0.63286, 4071463.241], [0.05843, -0.9721, 0.22716, 1406636.117], [0.63832, 0.21133, 0.74019, 4688170.68283], [0.0, 0.0, 0.0, 1.0]]

**Comment by shawrby** [comment]
@TamasMatuszka 
What's the annotation method for the 3D bounding box?
And, Is it based on the Body coordinate system?

**Comment by TamasMatuszka** [comment]
@shawrby 
Yes, the annotation is based on the body coordinate system. 

You can find the details of the annotation process in Section 3.3 of the paper:
https://arxiv.org/pdf/2211.09445.pdf
