### ISSUE TITLE
Weird annotation

### ISSUE THREAD

**Issue by shawrby** [aimotive/aimotive-dataset-loader#2]
@TamasMatuszka 

I'm now training an object detection model with aimotive dataset.
However, the training did not go well, so when I checked some datasets, they were annotated weirdly as shown below.

['Car' Annotation on Image plane]
![image](https://user-images.githubusercontent.com/54407464/206135658-04852ae5-4ec2-4a3b-a442-d8dcce23d06a.png)

['Car' Annotation on 3D plane]
![image](https://user-images.githubusercontent.com/54407464/206135902-9f09285a-6d29-4957-b823-4646a95e3524.png)

* Scene & frame: aimotive_dataset/train/urban/20210729-162718-00.16.45-00.17.00@Yoda/sensor/camera/F_MIDLONGRANGECAM_CL/F_MIDLONGRANGECAM_CL_0015173.jpg

**Comment by TamasMatuszka** [comment]
Hi @shawrby,

The training dataset has been annotated using an automatic annotation method. The resulting annotations were manually quality checked but apparently, some noise still might be included in the dataset.

Thank you for noticing the error, we will revise this sequence.

What kind of model did you train? We have trained several multimodal models in this repository:
https://github.com/aimotive/mm_training/tree/main/exps/configs

I'll upload the weights and config files for inference in the next week, maybe you can use them as a base for your training script or for getting ideas.

**Comment by TamasMatuszka** [comment]
@shawrby I uploaded the weights and config files, you can find them here:
https://github.com/aimotive/mm_training

You will need to change the 'data_root' and 'ckpt_path' variables. Furthermore, you can fine-tune the model performance by changing the 'score_threshold' variable of the bbox_coder dict.
