### ISSUE TITLE
Radar data is extremely sparse - not HD

### ISSUE THREAD

**Issue by SM1991CODES** [aimotive/aimotive-dataset-loader#4]
Hi,

I had the idea that the radar used was high definition and should given a much denser point cloud than conventional radars.
However, I see the point clouds are very sparse as seen below.

1) Lidar
![image](https://github.com/aimotive/aimotive-dataset-loader/assets/69435296/db9839a0-d1fb-4c4d-b838-d09600042089)

2) Radar - Front
![image](https://github.com/aimotive/aimotive-dataset-loader/assets/69435296/84e451bf-8020-458e-91c1-78bf4dd97708)

Am I doing something wrong here? Please explain this.

Best Regards
Sambit

**Comment by TamasMatuszka** [comment]
Hi @SM1991CODES,

We used SmartMicro UMRR-11 during the recordings of the dataset, which is not a high-definition radar. Its output is sparse (<100 data points/scene), but we found it beneficial in long-range detections and in adverse weather (e.g., rain).
